# Generated by Django 5.0.2 on 2024-03-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorhome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorhomes/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('motorhome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='motorhomes.motorhome')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start', models.DateTimeField()),
                ('rental_end', models.DateTimeField()),
                ('motorhome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhomes.motorhome')),
            ],
        ),
    ]
